# Generated by Django 4.2.13 on 2024-05-25 06:47

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Place",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150)),
                ("address", models.CharField(blank=True, max_length=150, null=True)),
                ("city", models.CharField(blank=True, max_length=150, null=True)),
                ("country", models.CharField(blank=True, max_length=150, null=True)),
            ],
        ),
    ]
