# Generated by Django 4.2.13 on 2024-06-05 04:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("medias", "0001_initial"),
        ("galleries", "0004_remove_gallery_place"),
        ("places", "0003_alter_place_gallery"),
    ]

    operations = [
        migrations.AddField(
            model_name="place",
            name="photo",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="photos",
                to="medias.photo",
            ),
        ),
        migrations.AddField(
            model_name="place",
            name="video",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="videos",
                to="medias.video",
            ),
        ),
        migrations.AlterField(
            model_name="place",
            name="gallery",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="places",
                to="galleries.gallery",
            ),
        ),
    ]
