# Generated by Django 4.2.13 on 2024-05-31 13:16

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0007_user_is_email_alter_user_is_active"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="user",
            managers=[],
        ),
    ]
