# Generated by Django 4.2.13 on 2024-06-05 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0009_alter_user_managers"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_profile",
            field=models.BooleanField(default=False),
        ),
    ]
