# Generated by Django 4.2.13 on 2024-06-06 00:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0010_user_is_profile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="nickname",
            field=models.CharField(blank=True, max_length=150, null=True, unique=True),
        ),
    ]
