# Generated by Django 4.2.13 on 2024-05-25 06:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("galleries", "0001_initial"),
        ("places", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="gallery",
            name="photo_grapher",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="gallery",
            name="place",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="places.place",
            ),
        ),
    ]
