# Generated by Django 4.2.13 on 2024-06-05 04:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("galleries", "0003_alter_gallery_photo_grapher"),
    ]

    operations = [
        migrations.RemoveField(model_name="gallery", name="place",),
    ]
