# Generated by Django 4.2.13 on 2024-05-25 06:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("brands", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Camera",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("megapixels", models.DecimalField(decimal_places=2, max_digits=5)),
                ("iso", models.CharField(max_length=50)),
                ("image_stabilization", models.BooleanField(default=False)),
                ("price_won", models.DecimalField(decimal_places=2, max_digits=20)),
                ("price_dollar", models.DecimalField(decimal_places=2, max_digits=20)),
                ("release_date", models.DateField()),
                (
                    "brand",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="brands.brand",
                    ),
                ),
            ],
        ),
    ]
