# Generated by Django 4.2.13 on 2024-06-05 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cameras", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="camera",
            name="iso",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="camera",
            name="megapixels",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=5, null=True
            ),
        ),
        migrations.AlterField(
            model_name="camera",
            name="price_dollar",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=20, null=True
            ),
        ),
        migrations.AlterField(
            model_name="camera",
            name="price_won",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=20, null=True
            ),
        ),
        migrations.AlterField(
            model_name="camera",
            name="release_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
